### ISSUE TITLE
Conditional Integration with other packages

### ISSUE THREAD

**Issue by ChrisRackauckas** [IntelLabs/Sparso#1]
Hey, I am really interested in integrating Sparso's capabilities with DifferentialEquations.jl. However, from what I understand of

> Sparso detects sparse matrix operations and redirects where possible to an optimized implementation provided by the MKL or SpMP library.

it seems that Spraso works by overloading the operators for sparse matrix operations. While for scripts this works, this seems like it would be a problem in packages if I want to use this conditionally. Being able to "conditionally" enable this package is key to it being integrated since there's no way I can expect most users to build and get this running, but it would be a really nice offering and give good speedups in PDE solvers, so I would like the option.

Right now my method for conditional dependencies is simple and uses the following functions:

``` julia
type backend{T} end
init_package(sym::Symbol) = init_package(backend{sym}())
```

in the top scope of the module so that, for example, initializing the Sundials package uses:

``` julia
init_package(b::backend{:Sundials}) = @eval begin
      import Sundials
      export Sundials
    end
```

However, all the packages I've done this for add new functions, and don't do operator overloading. I am wondering if something like

``` julia
init_package(b::backend{:Sparso}) = @eval begin
        using Sparso
        export Sparso
    end
```

and then calling `init_package(:Sparso)` would do the overloading correctly.

Do you guys have any other ideas on good ways to conditionally enhance packages with Sparso?

**Comment by ronghongbo** [comment]
Hello Christopher,

It is a nice idea to conditionally turn on/off Sparso. Sparso has an option to turn on/off its features. For example, if you look at test/correctness/call-replacement-test1.jl, you will see
            
          set_options(SA_ENABLE, SA_VERBOSE, SA_USE_SPMP, SA_REPLACE_CALLS)

If you do not set SA_ENABLE, it is by default off: that turns off Sparso entirely. If you do not set SA_REPLACE_CALLS, it will not replace calls with MKL or SPMP. 

These options are defined in src/globals.jl. Their default values are defined as
      sparse_acc_enabled                      = false
           ......
      replace_calls_enabled                   = false

Let me know if there is any other issue.

Hongbo

**Comment by ChrisRackauckas** [comment]
Wouldn't turning on and off Spraso like that require a user to have Sparso.jl installed? If so, that wouldn't work.

**Comment by ronghongbo** [comment]
Inside your init_package above, you can add set_options(...) to turn on sparso features.

**Comment by ChrisRackauckas** [comment]
Oh I see. That should work. I'll give it a try.

**Comment by ChrisRackauckas** [comment]
Closed do to using a better system.
